# -*- coding: utf-8 -*-
"""
/***************************************************************************
 PolygonFromMapExtent
                                 A QGIS plugin
 A lightweight QGIS plugin to make a polygon from the current map extent.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2022-09-27
        copyright            : (C) 2022 by Matt Needle
        email                : m_needle@hotmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load PolygonFromMapExtent class from file PolygonFromMapExtent.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .polygon_from_map_extent import PolygonFromMapExtent
    return PolygonFromMapExtent(iface)
